import plurisubharmonic_extremal_functions_pluricomplex_green_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace plurisubharmonic_extremal_functions_pluricomplex_green_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end plurisubharmonic_extremal_functions_pluricomplex_green_theorem_canonical_lane_mathlib
end HautevilleHouse
